# Generated by Django 3.1.5 on 2021-02-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop')], default='', max_length=15)),
                ('processor', models.CharField(max_length=250)),
                ('ram', models.CharField(default='', max_length=250)),
                ('screen_size', models.CharField(default='', max_length=200)),
                ('color', models.CharField(default='', max_length=250)),
                ('hd_capacity', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
